on:
  push:
    branches:
      - 'email'

name: Email sent experiment
jobs:
  email:
    name: Email
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: '[Github Actions build runner] apk built success fully'
          to: hackerhgl@gmail.com
          secure: true
          body: 'This is an automated mail sent via github actions runner.\nscript author @hackerhgl'
          from: hiqbal@voxlabs.io
          reply_to: hiqbal@voxlabs.io
          priority: high
