on:
  push:
    branches:
      - 'email'

name: Email sent experiment
jobs:
  email:
    name: Email
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: npm i
      - name: Decode service account base64
        run: echo "$ACCOUNT_ENV64" | base64 -d > ./service-key.json
        env:
          ACCOUNT_ENV64: ${{ secrets.SERVICE_ACCOUNT64 }}

      - name: Send emails
        run: node mail --to=$TO --from=$FROM --user=$USERNAME --key=$PASSWORD
        # run: node mail --to=$TO --from=$FROM --user=$USERNAME --password=$PASSWORD
        env:
          TO: ${{ secrets.MAIL_TO }}
          FROM: ${{ secrets.MAIL_FROM }}
          USERNAME: ${{ secrets.MAIL_USERNAME }}
          PASSWORD: ${{ secrets.MAIL_PASSWORD }}
