on:
  push:
    branches:
      - 'email'

name: Email sent experiment
jobs:
  email:
    name: Email
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: devellany/send-mailer
        with:
          host: smtp.google.com
          # Optional port (defaults to 465)
          port: 465
          account: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: devellany
          from: hiqbal@voxlabs.io
          to: devellay@dico.me
          subject: mail title.
          body: your messages.
          # Optional content type (defaults to text/plain)
          contentType: text/plain
          # Optional attachment files (JSON type. require property 'path')
          # attachments: '[{"path":"README.md"}]'
      # - name: Send mail
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: ${{secrets.MAIL_USERNAME}}
      #     password: ${{secrets.MAIL_PASSWORD}}
      #     subject: '[Github Actions build runner] apk built success fully'
      #     to: hackerhgl@gmail.com
      #     secure: true
      #     body: 'This is an automated mail sent via github actions runner.\nscript author @hackerhgl'
      #     from: hiqbal@voxlabs.io
      #     reply_to: hiqbal@voxlabs.io
      #     priority: high
