on:
  push:
    branches:
      - "master"

name: Fun release builds
jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          # flutter-version: '2.2.2'
          channel: 'stable'
      - uses: actions/checkout@v2
        with:
          ref: 'runner'
          path: 'app'
          token: ${{ secrets.PAT_TOKEN }}
          repository: 'sastaTicket/sastaticket-mobile-app'


      - name: Fetch packages
        run: cd app && flutter pub get

      - name: Build dev release apk
        run: cd app && flutter build apk --flavor dev
      - uses: actions/upload-artifact@v2
        with:
          name: app-dev-release.apk
          path: app/build/app/outputs/flutter-apk/app-dev-release.apk

      - name: Build stage release apk
        run: cd app && flutter build apk --flavor stage
      - uses: actions/upload-artifact@v2
        with:
          name: app-stage-release.apk
          path: app/build/app/outputs/flutter-apk/app-stage-release.apk

      - name: Build qa release apk
        run: cd app && flutter build apk --flavor qa
      - uses: actions/upload-artifact@v2
        with:
          name: app-qa-release.apk
          path: app/build/app/outputs/flutter-apk/app-qa-release.apk

      - name: Build prod release apk
        run: cd app && flutter build apk --flavor prod
      - uses: actions/upload-artifact@v2
        with:
          name: app-prod-release.apk
          path: app/build/app/outputs/flutter-apk/app-prod-release.apk

      - name: Build prod release app bundle
        run: cd app && flutter build appbundle --flavor prod

      # - name: Create Android Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: 'app/build/app/outputs/apk/release/app-release.apk'
      #     token: ${{ secrets.TOKEN }}
      #     allowUpdates: true
