on:
  push:
    branches:
      - 'master'

name: Fun release builds
jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: ['dev', 'qa', 'stage', 'prod']

    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          key: 'java-12x-cache'
          restore-keys: |
            'java-12x-cache'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.2'
          key: 'flutter-222-cache'
          restore-keys: |
            'flutter-222-cache'
          # channel: 'stable'
      - uses: actions/checkout@v2
        with:
          ref: 'runner'
          path: 'app'
          token: ${{ secrets.PAT_TOKEN }}
          repository: 'sastaTicket/sastaticket-mobile-app'

      - name: Create base64 file
        run: echo "$BASE64" | base64 -d > ./sastaticket-prod.keystore
        env:
          BASE64: ${{ secrets.STORE64 }}

      # run: echo ${{ secrets.STORE64 }} > base64.text
      # - name: Decode base64 file
      #   run: openssl base64 -d -in base64.text -out sastaticket-prod.keystore

      - name: Fetch packages
        run: cd app && flutter pub get

      - name: Build ${{ matrix.flavor }} release apk
        run: cd app && flutter build apk --flavor ${{ matrix.flavor }}
      - uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.flavor }}-release.apk
          path: app/build/app/outputs/flutter-apk/app-${{ matrix.flavor }}-release.apk
